project_id = "csbytipwverpjxojulla"

[functions.reset-user-password]
verify_jwt = false

[functions.send-newsletter-notification]
verify_jwt = false

[functions.newsletter-confirm]
verify_jwt = false

[functions.save-newsletter-subscriber]
verify_jwt = false